version: "3.8"

services:
  nginx:
    image: ghcr.io/cssnr/docker-nginx-proxy:latest
    environment:
      - SERVICE_NAME=app # name of app container
      - SERVICE_PORT=8000 # port exposed on app
    ports:
      - "${PORT:-80}:80" # Host PORT : Container (must be :80)

  app:
    image: your-app-image # listens on port 8000
